[metadata]
name = ha_dual_ros2
version = 0.2.1
description = Thin ROS2 wrapper: robot_description / URDF → HA Dual socket
maintainer = Stanislav Byriukov <stanislav@hardwareatom.local>
license = Apache-2.0

[options]
packages = find:
zip_safe = false
install_requires =
    setuptools

[options.entry_points]
console_scripts =
    dual_from_description = ha_dual_ros2.cli:main
    dual_node = ha_dual_ros2.dual_node:main

[options.package_data]
* = *.md
